version: '3'

services:
  challenge:
    build: src
    deploy:
      replicas: 2
    ports:
      - "2222:22"
    environment:
      DELETE_CRON: "*/2 * * * *"
    labels:
      #      kompose.service.type: LoadBalancer
      kompose-ex.service.type: ingress-nginx
      kompose.image-pull-policy: Always
      kompose-ex.service.expose: name.challenge.ctf.today
    restart: always
