services:
  - docker:dind

default:
  tags:
    - docker
  image: realgam3/kompose-ex:cicd
  interruptible: true

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  variables:
    NAMESPACE: $CI_PROJECT_NAME
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" $CI_REGISTRY
    - docker compose -f docker-compose.yml build
    - docker compose -f docker-compose.yml push
    - kompose-ex deploy -f docker-compose.yml -o k8s/ --deny-ingress --deny-egress-cidr 169.254.0.0/16 --deny-egress-cidr 10.100.0.1/32 -d --namespace $NAMESPACE --create-namespace --rollout-restart --patch-ingress --eks-kubeconfig $AWS_EKS_CLUSTER
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
