version: '3'

services:
  backend:
    build: backend
    deploy:
      replicas: 2
    ports:
      - "3000:3000"
    labels:
      kompose.image-pull-secret: registry-gitlab
      kompose.image-pull-policy: Always
      kompose.service.expose: web.challenge.ctf.today
      kompose.service.expose.ingress-class-name: nginx
      kompose.service.expose.tls-secret: tls-nginx-ingress
    restart: always

  queue:
    image: rabbitmq:3.9.7-alpine
    expose:
      - "5672"
    restart: always

  bot:
    build: bot
    deploy:
      replicas: 4
    depends_on:
      - queue
    restart: always
