version: '3'

services:
  backend:
    build: backend
    deploy:
      replicas: 2
    ports:
      - "3000:3000"
    labels:
      kompose.image-pull-policy: Always
      kompose.service.expose: web.challenge.ctf.today
      kompose-ex.service.expose.tls: "true"
      kompose.service.expose.ingress-class-name: nginx
    restart: always

  queue:
    image: rabbitmq:3.9.7-alpine
    expose:
      - "5672"
    restart: always

  bot:
    image: realgam3/puppeteer-bot:latest
    deploy:
      replicas: 4
    depends_on:
      - queue
    volumes:
      - "./bot/config.js:/usr/src/app/config.js"
    labels:
      kompose.volume.type: configMap
    restart: always
