version: '3'

services:
  challenge:
    build: src
    deploy:
      replicas: 2
    ports:
      - "3000:3000"
    environment:
      DELETE_CRON: "*/2 * * * *"
    labels:
      kompose.image-pull-policy: Always
      kompose.service.expose: name.challenge.ctf.today
      kompose.service.expose.ingress-class-name: nginx
      kompose-ex.service.expose.tls: "true"
    restart: always
